name:                hsqoi
version:             0.1.0.0
github:              "0xd34df00d/hsqoi"
license:             BSD3
author:              "Georg Rudoy"
maintainer:          "0xd34df00d@gmail.com"
copyright:           "2021 Georg Rudoy"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/0xd34df00d/hsqoi#readme>

dependencies:
- base >= 4.15 && < 5
- array
- binary
- binary-generic-combinators >= 0.4.4.0
- bytestring
- bytestring-mmap
- vector

ghc-options:
- -Wall

library:
  source-dirs: src

executables:
  hsqoi-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -rtsopts
    dependencies:
    - hsqoi
    - JuicyPixels

tests:
  hsqoi-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hsqoi
    - hspec
    - QuickCheck
