resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/18/18.yaml
#resolver: nightly-2021-12-04
packages:
- .
extra-deps:
- binary-generic-combinators-0.4.4.0
